name: Update Workflow

on:
  push:

jobs:
  update:
    name: Updater
    runs-on: ubuntu-latest
    steps:
      - name: Puller
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /pub/${{ secrets.USERNAME }}
            cd cmsc389T-web-template
            git pull